"""empty message

Revision ID: 20d84b128449
Revises: aae00ff010d3
Create Date: 2021-09-07 16:29:44.875108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d84b128449'
down_revision = 'aae00ff010d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_guardian',
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=25), nullable=False),
    sa.Column('lname', sa.String(length=25), nullable=False),
    sa.Column('pnumber', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('pg_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=25), nullable=False),
    sa.Column('lname', sa.String(length=25), nullable=False),
    sa.Column('pnumber', sa.String(length=11), nullable=False),
    sa.Column('department', sa.Integer(), nullable=False),
    sa.Column('formclass', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('accountnumber', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('dataofbirth', sa.String(length=50), nullable=False),
    sa.Column('subjectteaching', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['formclass'], ['all_classes.class_id'], ),
    sa.ForeignKeyConstraint(['subjectteaching'], ['subject.subject_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=25), nullable=False),
    sa.Column('lname', sa.String(length=25), nullable=False),
    sa.Column('parentorguardian', sa.Integer(), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=False),
    sa.Column('presentclass', sa.Integer(), nullable=False),
    sa.Column('classteacher', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address'], ['parent_guardian.pg_id'], ),
    sa.ForeignKeyConstraint(['classteacher'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['contact'], ['parent_guardian.pg_id'], ),
    sa.ForeignKeyConstraint(['parentorguardian'], ['parent_guardian.pg_id'], ),
    sa.ForeignKeyConstraint(['presentclass'], ['all_classes.class_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('staff')
    op.drop_table('parent_guardian')
    # ### end Alembic commands ###
