"""empty message

Revision ID: aae00ff010d3
Revises: 309f156f5d20
Create Date: 2021-09-07 16:16:19.415298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae00ff010d3'
down_revision = '309f156f5d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('classes', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('section',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('software_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subject',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_table('software_user')
    op.drop_table('section')
    op.drop_table('department')
    op.drop_table('all_classes')
    # ### end Alembic commands ###
